from backend.downloader.aoashi import AoAshiDl
from backend.downloader.gekkou import GekkouDl
from backend.downloader.mangadex import MangaDexDl
from backend.downloader.mangalivre import MangaLivreDl
from backend.downloader.mangafire import MangaFireDl
from backend.downloader.op import OpScansDl
from backend.downloader.opex import OpexDl
from backend.downloader.taosect import TaoSectScanDl
from backend.downloader.tcb import TCBScansDl